<a href="https://colab.research.google.com/github/aashinshrestha77/Computational-Mathematics-/blob/main/CMW6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name: Aashin Shrestha**

**Student ID: 2603726**

PART 1

1) Create a 2D NumPy array using np.array() and then print its properties like shape, size, and datatype.

In [ ]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Array:\n", arr)

print("\nShape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (total elements):", arr.size)
print("Data type:", arr.dtype)
print("\nItem size (bytes):", arr.itemsize)
print("Total bytes:", arr.nbytes)
print("Memory layout flags:\n", arr.flags)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)
Number of dimensions: 2
Size (total elements): 9
Data type: int64

Item size (bytes): 8
Total bytes: 72
Memory layout flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



2) Create a matrix filled with a constant value using np.ones() multiplied by 3.

In [ ]:
matrix = np.ones((4,5)) * 3.0
print(matrix)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


3.  Other way to create the same matrix as above.

In [ ]:
import numpy as np
matrix = np.full((4,5), 3.0)
print(matrix)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


4. Constructing a matrix using given formula.

In [ ]:
A = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        A[i,j] = 0.5 * abs((i+1) - 3*(j+1))

print(A)

[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]


5. Using the function numpy.diag() to construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4].

In [ ]:
import numpy as np

diag_matrix = np.diag([1,2,3,4])
print(diag_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


6. Using ndarray to construct a matrix of shape (4,5) with whatever elements, and then slice it to obtain a matrix of shape (3,3) that contains only upper-left portion of the original matrix.

In [ ]:
import numpy as np

matrix = np.arange(1, 21).reshape(4,5)
print("Original Matrix:\n", matrix)

sliced_matrix = matrix[:3, :3]
print("\nSliced Matrix (3x3 upper-left):\n", sliced_matrix)

Original Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sliced Matrix (3x3 upper-left):
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


Part 2

1. Ans: Addition of two matrices of different sizes can not be done because shapes (3×3) and (2×3) are not compatible.

2. Compute matrix-vector multiplication using loops and compare with np.dot().

In [5]:
import numpy as np

def dot_product(vec1, vec2):

    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(mat, vec):
    m, n = mat.shape
    p, q = vec.shape

    assert n == p, "The matrix and vector are not compatible for multiplication!"

    result = np.zeros((m, q), dtype=float)

    for i in range(m):
        result[i] = dot_product(mat[i, :], vec)

    return result

mat1 = np.full((3, 3), 3, dtype=int)
vec1 = np.full((3, 1), 2, dtype=int)

print("Matrix = \n", mat1)
print("Vector = \n", vec1)

result1 = matrix_vector_product(mat1, vec1)
print("Result1 (Manual) = \n", result1)

result2 = mat1 @ vec1
print("Result2 (NumPy @) = \n", result2)

Matrix = 
 [[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
 [[2]
 [2]
 [2]]
Result1 (Manual) = 
 [[18.]
 [18.]
 [18.]]
Result2 (NumPy @) = 
 [[18]
 [18]
 [18]]


3. Python function that performs Matrix-Matrix
product.

In [6]:
def matrix_matrix_product(matA, matB):
    m, n = matA.shape
    p, q = matB.shape

    assert n == p, "Matrices are not compatible for multiplication!"

    result = np.zeros((m, q), dtype=float)

    for i in range(m):
        for j in range(q):
            result[i, j] = dot_product(matA[i, :], matB[:, j])

    return result

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

res_manual = matrix_matrix_product(A, B)

res_numpy = A @ B

print("Manual Result:\n", res_manual)
print("NumPy Result:\n", res_numpy)

Manual Result:
 [[19. 22.]
 [43. 50.]]
NumPy Result:
 [[19 22]
 [43 50]]


 4. Python function that checks if it is a symmetric matrix using transpose of matrix.

In [ ]:
import numpy as np

def is_symmetric(matrix):
    arr = np.array(matrix)

    if arr.shape[0] != arr.shape[1]:
        return False

    return np.array_equal(arr, arr.T)

symmetric_matrix = [[1, 2, 3],
                    [9, 4, 5],
                    [3, 5, 6]]

print(is_symmetric(symmetric_matrix))

False
